/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param blogPost The GUID of the blogPost the parent comment is on.
 * @param text The text of the reply being posted.
 * @param replyTo The GUID of the parent CommentModel being replied to.
 */


data class CommentV3ReplyRequest (

    /* The GUID of the blogPost the parent comment is on. */
    @Json(name = "blogPost")
    val blogPost: kotlin.String,

    /* The text of the reply being posted. */
    @Json(name = "text")
    val text: kotlin.String,

    /* The GUID of the parent CommentModel being replied to. */
    @Json(name = "replyTo")
    val replyTo: kotlin.String

) {


}

