/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param username 
 * @param badges Badge IDs awarded to the owning user. Not in the upstream spec.
 */


data class CreatorModelV3Owner (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "username")
    val username: kotlin.String,

    /* Badge IDs awarded to the owning user. Not in the upstream spec. */
    @Json(name = "badges")
    val badges: kotlin.collections.List<kotlin.String>? = null

) {


}

