/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param hasVideo 
 * @param videoDuration 
 * @param hasAudio 
 * @param audioDuration 
 * @param hasPicture 
 * @param videoCount 
 * @param audioCount 
 * @param pictureCount 
 * @param hasGallery 
 * @param galleryCount 
 * @param isFeatured 
 * @param displayDuration Duration in seconds of the primary video on a post, distinct from videoDuration (which sums every video attachment). Use this on cards/feeds for multi-video posts.
 */


data class PostMetadataModel (

    @Json(name = "hasVideo")
    val hasVideo: kotlin.Boolean,

    @Json(name = "videoDuration")
    val videoDuration: java.math.BigDecimal,

    @Json(name = "hasAudio")
    val hasAudio: kotlin.Boolean,

    @Json(name = "audioDuration")
    val audioDuration: java.math.BigDecimal,

    @Json(name = "hasPicture")
    val hasPicture: kotlin.Boolean,

    @Json(name = "videoCount")
    val videoCount: kotlin.Int? = null,

    @Json(name = "audioCount")
    val audioCount: kotlin.Int? = null,

    @Json(name = "pictureCount")
    val pictureCount: kotlin.Int? = null,

    @Json(name = "hasGallery")
    val hasGallery: kotlin.Boolean? = null,

    @Json(name = "galleryCount")
    val galleryCount: kotlin.Int? = null,

    @Json(name = "isFeatured")
    val isFeatured: kotlin.Boolean? = null,

    /* Duration in seconds of the primary video on a post, distinct from videoDuration (which sums every video attachment). Use this on cards/feeds for multi-video posts. */
    @Json(name = "displayDuration")
    val displayDuration: kotlin.Int? = null

) {


}

