/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.DiscordRoleModel
import com.coulterpeterson.floatnative.openapi.models.DiscordServerModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param description 
 * @param price 
 * @param currency 
 * @param logo 
 * @param interval 
 * @param featured 
 * @param discordServers 
 * @param discordRoles 
 * @param priceYearly 
 * @param allowGrandfatheredAccess 
 */


data class SubscriptionPlanModel (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String,

    @Json(name = "price")
    val price: kotlin.String?,

    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "logo")
    val logo: kotlin.String?,

    // Real responses observed in production omit `interval` on subscriptionPlans
    // attached to creators in /api/v3/content/creator/list (e.g. LTT). Marked
    // optional via packages/openapi/spec-overlay.json so future regenerations
    // stay loose.
    @Json(name = "interval")
    val interval: kotlin.String? = null,

    @Json(name = "featured")
    val featured: kotlin.Boolean,

    @Json(name = "discordServers")
    val discordServers: kotlin.collections.List<DiscordServerModel>,

    @Json(name = "discordRoles")
    val discordRoles: kotlin.collections.List<DiscordRoleModel>,

    @Json(name = "priceYearly")
    val priceYearly: kotlin.String? = null,

    @Json(name = "allowGrandfatheredAccess")
    val allowGrandfatheredAccess: kotlin.Boolean? = null

) {


}

