/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.ChannelModel
import com.coulterpeterson.floatnative.openapi.models.CreatorModelV2
import com.coulterpeterson.floatnative.openapi.models.ImageModel
import com.coulterpeterson.floatnative.openapi.models.PostMetadataModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Variant of BlogPostModelV3 returned inside watch-history entries. Differs from the home-feed shape in that videoAttachments / audioAttachments / pictureAttachments / galleryAttachments are arrays of string IDs rather than full attachment objects.
 *
 * @param id 
 * @param guid 
 * @param title 
 * @param text 
 * @param type 
 * @param channel 
 * @param tags 
 * @param attachmentOrder 
 * @param metadata 
 * @param releaseDate 
 * @param likes 
 * @param dislikes 
 * @param score 
 * @param comments 
 * @param creator 
 * @param wasReleasedSilently 
 * @param isAccessible 
 * @param thumbnail 
 * @param videoAttachments 
 * @param audioAttachments 
 * @param pictureAttachments 
 * @param galleryAttachments 
 */


data class WatchHistoryBlogPost (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "guid")
    val guid: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "channel")
    val channel: ChannelModel,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    @Json(name = "attachmentOrder")
    val attachmentOrder: kotlin.collections.List<kotlin.String>,

    @Json(name = "metadata")
    val metadata: PostMetadataModel,

    @Json(name = "releaseDate")
    val releaseDate: java.time.OffsetDateTime,

    @Json(name = "likes")
    val likes: kotlin.Int,

    @Json(name = "dislikes")
    val dislikes: kotlin.Int,

    @Json(name = "score")
    val score: kotlin.Int,

    @Json(name = "comments")
    val comments: kotlin.Int,

    @Json(name = "creator")
    val creator: CreatorModelV2,

    @Json(name = "wasReleasedSilently")
    val wasReleasedSilently: kotlin.Boolean,

    @Json(name = "isAccessible")
    val isAccessible: kotlin.Boolean,

    @Json(name = "thumbnail")
    val thumbnail: ImageModel? = null,

    @Json(name = "videoAttachments")
    val videoAttachments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "audioAttachments")
    val audioAttachments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "pictureAttachments")
    val pictureAttachments: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "galleryAttachments")
    val galleryAttachments: kotlin.collections.List<kotlin.String>? = null

) {


}

