/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.coulterpeterson.floatnative.openapi.models

import com.coulterpeterson.floatnative.openapi.models.WatchHistoryBlogPost

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One entry in /api/v3/content/history. Records that a user watched a piece of content along with their last-known progress. Not in the upstream spec.
 *
 * @param userId 
 * @param contentId 
 * @param contentType 
 * @param progress Last-known playback progress in seconds.
 * @param updatedAt 
 * @param blogPost 
 */


data class WatchHistoryEntry (

    @Json(name = "userId")
    val userId: kotlin.String,

    @Json(name = "contentId")
    val contentId: kotlin.String,

    @Json(name = "contentType")
    val contentType: kotlin.String,

    /* Last-known playback progress in seconds. */
    @Json(name = "progress")
    val progress: kotlin.Int,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "blogPost")
    val blogPost: WatchHistoryBlogPost

) {


}

